### ISSUE TITLE
Error when you add an invoice address for an existing customer

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#51]
When you add another address for an existing customer the following error occurs when you try to save the record:
![f95457bd-a3d5-4b04-bacc-afd1805275ea](https://user-images.githubusercontent.com/14073662/35551137-7c7f98b8-0596-11e8-946c-f409b9c3f50c.jpeg)

**Comment by DanielMaimba** [comment]
@mdi-odoo please can you attend to this urgently and the return to your current work which you are busy with.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/fe412d0ce3538dcabb15ce3f2621bd481913c800 .

**Comment by DanielMaimba** [comment]
@mdi-odoo @avp-odoo I have tested this and I am still experiencing the same error. Please check again.
