### ISSUE TITLE
Wrong credit or debit value in accounting entry ! when manually importing bank statement (master bank statement)

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#59]
When I attempt to import a bank statement manually (master bank statement) we get the following error: Wrong credit or debit value in accounting entry ! 

Please see screenshot of the error.

<img width="1016" alt="screen shot 2018-02-08 at 06 41 33" src="https://user-images.githubusercontent.com/14073662/35955943-55dc10e0-0c9b-11e8-84c5-720fdf5d6b46.png">

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/f2ed010fe45c7a918b8cb5e60671eca4abd29c72 .

**Comment by DanielMaimba** [comment]
@mdi-odoo @avp-odoo  I have applied the latest update on inuka-dedicated and upgraded the module and I am still getting this error when I try to import the statement. This issue seems like its not yet fixed.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/3477e9cf0197e5343cc5d9c1454b56369382e1d3 .
