### ISSUE TITLE
Creation/update: a mandatory field is not correctly set  [object with reference: Sales Channel - crm.team] 

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#64]
When you click on the 'Create Sales Order' button from a helpdesk ticket, we are getting the error (Creation/update: a mandatory field is not correctly set  [object with reference: Sales Channel - crm.team] )

Please can you set the default team to the team called Orders.

![image](https://user-images.githubusercontent.com/14073662/36197492-8e682a26-117c-11e8-89f5-d128c36d8cb1.png)

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/882a1a5972804f8dfeace8506df280dd9482297f .

**Comment by DanielMaimba** [comment]
@mdi-odoo we are still getting this error. It however seems to be happening when the Helpdesk Team = Orders, for the other helpdesk tickets with a different team all seems fine. Please can you look into this again.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/3ff34333ff3d8f3ec00002f9e54405f51351d21f .
