### ISSUE TITLE
URGENT: Bank Integration Process Issues

### ISSUE THREAD

**Issue by DanielMaimba** [StrategicDimensions/inuka#68]
The bank integration is becoming an issue (banktransactions@inuka.co.za & bankstatements@inuka.co.za)

I setup another system https://strategicdimensions-inuka-bank-integration.odoo.com
- When I uninstall the Inuka module - the helpdesk tickets are created fine with the attachments
- When I install the Inuka module - the helpdesk tickets are not created on the system

This is proving that there is something in our code that is causing issues. Maybe we are interrupting the odoo process of creating the helpdesk ticket with something in our code. So we have to maybe allow the normal ticket creation process to continue and then have a cron which runs separately to process the attachments

Please look into this urgently for me

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/1aefc589e3123f4212e70d78c2fa171f5d0556dd .

**Comment by DanielMaimba** [comment]
This is still not working please review @mdi-odoo 

2018-02-21 20:14:08,511 4 INFO strategicdimensions-inuka-bank-integration-master-23943 odoo.addons.fetchmail.models.fetchmail: start checking for new emails on imap server INUKA
2018-02-21 20:14:10,316 4 INFO strategicdimensions-inuka-bank-integration-master-23943 odoo.addons.mail.models.mail_thread: No matching user_id for the alias banktransactions
2018-02-21 20:14:10,663 4 INFO strategicdimensions-inuka-bank-integration-master-23943 odoo.addons.mail.models.mail_thread: Routing mail from "noreply@fnb.co.za" to with Message-Id <1292328395.3806.1519182494337.JavaMail.seg2@fnb.co.za>: direct alias match: ('helpdesk.ticket', 0, {'team_id': 1}, 1, mail.alias(34,))
2018-02-21 20:14:11,641 4 ERROR strategicdimensions-inuka-bank-integration-master-23943 odoo.sql_db: bad query: b'UPDATE "res_partner_bank" SET "sanitized_acc_number"=\'0000062265854812\',"write_uid"=1,"write_date"=(now() at time zone \'UTC\') WHERE id IN (16)'
ERROR: duplicate key value violates unique constraint "res_partner_bank_unique_number"
DETAIL: Key (sanitized_acc_number, company_id)=(0000062265854812, 1) already exists.

2018-02-21 20:14:11,642 4 ERROR strategicdimensions-inuka-bank-integration-master-23943 odoo.sql_db: bad query: b'SELECT "ir_model_data".id FROM "ir_model_data" WHERE (("ir_model_data"."module" = \'mail\') AND ("ir_model_data"."name" = \'mt_note\')) ORDER BY "ir_model_data"."module" ,"ir_model_data"."model" ,"ir_model_data"."name" '
ERROR: current transaction is aborted, commands ignored until end of transaction block

2018-02-21 20:14:11,642 4 INFO strategicdimensions-inuka-bank-integration-master-23943 odoo.addons.fetchmail.models.fetchmail: Failed to process mail from imap server INUKA.
Traceback (most recent call last):
File "/home/odoo/src/user/inuka/models/helpdesk.py", line 102, in import_bank_statement
new_rec.import_file()
File "/home/odoo/src/enterprise/account_bank_statement_import_csv/wizard/account_bank_statement_import_csv.py", line 19, in import_file
return super(AccountBankStatementImport, self).import_file()
File "/home/odoo/src/odoo/addons/account_bank_statement_import/account_bank_statement_import.py", line 41, in import_file
currency, journal = self._find_additional_data(currency_code, account_number)
File "/home/odoo/src/odoo/addons/account_bank_statement_import/account_bank_statement_import.py", line 146, in _find_additional_data
journal.set_bank_account(account_number)
File "/home/odoo/src/odoo/addons/account/models/account.py", line 642, in set_bank_account
'partner_id': self.company_id.partner_id.id,
File "/home/odoo/src/odoo/odoo/models.py", line 3278, in create
record = self.browse(self._create(old_vals))
File "/home/odoo/src/odoo/odoo/models.py", line 3435, in _create
self.recompute()
File "/home/odoo/src/odoo/odoo/models.py", line 4811, in recompute
target._write(dict(vals))
File "/home/odoo/src/odoo/odoo/models.py", line 3096, in _write
cr.execute(query, params + (sub_ids,))
File "/home/odoo/src/odoo/odoo/sql_db.py", line 155, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 232, in execute
res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "res_partner_bank_unique_number"
DETAIL: Key (sanitized_acc_number, company_id)=(0000062265854812, 1) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/tools/cache.py", line 84, in lookup
r = d[key]
File "/home/odoo/src/odoo/odoo/tools/func.py", line 68, in wrapper
return func(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/tools/lru.py", line 44, in __getitem__
a = self.d[obj].me
KeyError: ('ir.model.data', , 'mail.mt_note')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/src/odoo/addons/fetchmail/models/fetchmail.py", line 179, in fetch_mail
res_id = MailThread.with_context(**additionnal_context).message_process(server.object_id.model, data[0][1], save_original=server.original, strip_attachments=(not server.attach))
File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 1296, in message_process
thread_id = self.message_route_process(msg_txt, msg, routes)
File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 1224, in message_route_process
new_msg = thread.message_post(subtype=subtype, partner_ids=partner_ids, **message_dict)
File "/home/odoo/src/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 1888, in message_post
attachment_ids = self._message_post_process_attachments(attachments, kwargs.pop('attachment_ids', []), values)
File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 1744, in _message_post_process_attachments
new_attachment = IrAttachment.create(data_attach)
File "/home/odoo/src/user/inuka/models/helpdesk.py", line 178, in create
self.env['helpdesk.ticket'].browse(res.res_id).import_bank_statement()
File "/home/odoo/src/user/inuka/models/helpdesk.py", line 105, in import_bank_statement
ticket.message_post(body=str(e))
File "/home/odoo/src/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
message = super(MailThread, self).message_post(body=body, subject=subject, message_type=message_type, subtype=subtype, parent_id=parent_id, attachments=attachments, content_subtype=content_subtype, **kwargs)
File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 1845, in message_post
subtype_id = self.env['ir.model.data'].xmlid_to_res_id(subtype)
File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_model.py", line 1325, in xmlid_to_res_id
return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "", line 2, in xmlid_lookup
File "/home/odoo/src/odoo/odoo/tools/cache.py", line 89, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_model.py", line 1303, in xmlid_lookup
xid = self.sudo().search([('module', '=', module), ('name', '=', name)])
File "/home/odoo/src/odoo/odoo/models.py", line 1407, in search
res = self._search(args, offset=offset, limit=limit, order=order, count=count)
File "/home/odoo/src/odoo/odoo/models.py", line 3692, in _search
self._cr.execute(query_str, where_clause_params)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 155, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 232, in execute
res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

2018-02-21 20:14:11,735 4 INFO strategicdimensions-inuka-bank-integration-master-23943 odoo.addons.fetchmail.models.fetchmail: Fetched 1 email(s) on imap server INUKA; 0 succeeded, 1 failed.

**Comment by mdi-odoo** [comment]
Fixed in revision: https://github.com/StrategicDimensions/inuka/commit/a944fd9597e1f306fbad68c004dee3fbc28c9fc3 .
